// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
        
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLlhREHrRbAsrgatuHk18uLfCxutUoXmQ',
    appId: '1:77297349549:web:3a78b9eddac124595be724',
    messagingSenderId: '77297349549',
    projectId: 'kids-gaming-a05c2',
    authDomain: 'kids-gaming-a05c2.firebaseapp.com',
    storageBucket: 'kids-gaming-a05c2.firebasestorage.app',
    measurementId: 'G-CHTWFCRNGD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8KJZyV9hSny_nm3ggOSovor0CVS4LUhQ',
    appId: '1:77297349549:android:1676bad3346ed34f5be724',
    messagingSenderId: '77297349549',
    projectId: 'kids-gaming-a05c2',
    storageBucket: 'kids-gaming-a05c2.firebasestorage.app',
  );
}
